import { Inter } from "next/font/google";
import "./globals.css";

const geistSans = Inter();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={`${geistSans.className} antialiased`}>{children}</body>
      </html>
    </>
  );
}
